### ISSUE TITLE
Error: yaml: line 3: did not find expected key

### ISSUE THREAD

**Issue by Alomanko** [ensi-platform/elc-workspace#22]
Здравствуйте. Пытаюсь установить workspace как сказано здесь https://github.com/ensi-platform/elc-workspace  но когда я начинаю выполнять sudo elc clone catalog-pim orders-oms, то у меня выскакивает ошибка Error: yaml: line 3: did not find expected key. Если я делаю это без sudo, то у меня выскакивает такая ошибка: Error: current workspace is not set.
Я делаю так, как сказано в инструкции, но я получаю ошибку, что я делаю не так и как это исправить? Спасибо.

**Comment by MadridianFox** [comment]
Добрый день.
Вызывать elc через sudo точно не стоит, программа на это не рассчитана и должна работать от обычного пользователя.
Ошибка `current workspace is not set` означает что не выбран конкретный воркспейс. Странно, ведь это происходит автоматически при выполнении команды `elc workspace add`.
Попробуйте явным образом выбрать воркспейс с помощью команды `elc workspace select <имя-воркспейса>`.
Если не получится, то откройте файл `~/.elc.yaml` и заполните там поле `current_workspace`.
Вот содержимое моего файла для примера
```
current_workspace: ensi
update_command: curl -sSL https://raw.githubusercontent.com/ensi-platform/elc/master/get.sh
  | sudo -E bash
workspaces:
- name: ensi
  path: /home/madridianfox/work/ensi/workspace/
  root_path: /home/madridianfox/work/ensi
```

**Comment by mashkovsky-ab** [comment]
Здравствуйте. Аналогичная проблема. Рекомендации выше не помогают. Проверил каждый yaml файл на проблемы с отступами, но ничего не помогает.
Даже в файле ~/.elc.yaml приводил к следующему формату:
```
current_workspace: ensi  
update_command: curl -sSL https://raw.githubusercontent.com/ensi-platform/elc/master/get.sh | sudo -E bash
workspaces:
  - name: ensi
    path: /home/madridianfox/work/ensi/workspace/
    root_path: /home/madridianfox/work/ensi
```
elc version 0.2.9

**Comment by mashkovsky-ab** [comment]
> Здравствуйте. Аналогичная проблема. Рекомендации выше не помогают. Проверил каждый yaml файл на проблемы с отступами, но ничего не помогает. Даже в файле ~/.elc.yaml приводил к следующему формату:
> 
> ```
> current_workspace: ensi  
> update_command: curl -sSL https://raw.githubusercontent.com/ensi-platform/elc/master/get.sh | sudo -E bash
> workspaces:
>   - name: ensi
>     path: /home/XXX/work/ensi/workspace/
>     root_path: /home/XXX/work/ensi
> ```
> 
> elc version 0.2.9

Проблема была в workspace/env.yaml
Нужно было убрать после `variables:` квадратные скобки `[]`

Пример корректного файла:
```
# here you can redefine any global variables from workspace.yaml
# it's not mandatory
variables:
  APPS_ROOT: /home/madridianfox/work/ensi/apps
  PACKAGES_PATH: /home/madridianfox/work/ensi/packages

# here you can add your local components or redefine any parameters of base components
components: {}
  # my-local-component:
  #   path: ${WORKSPACE_PATH}/apps/my-app
  #   variables:
  #     APP_IMAGE: app:v1
  # cms-cms:
  #   alias: my-local-alias
  #   tags:
  #     - my-additional-tag

```
